import Cover from "./Cover"
import React from "react"
// import Question from "./Question"
import {nanoid} from "nanoid"

function App() {

  const [quizData, setQuizData] = React.useState([]) // initialize with an empty box to fill
  const [test, setTest] = React.useState(true);




  React.useEffect(function(){
     fetch("https://opentdb.com/api.php?amount=5")
         .then(res => res.json())
         .then(data => setQuizData(data.results.map( each => {
          return {
            question: each.question,
            correct: { id: nanoid(), answer: each.correct_answer, selected: false },
            incorrect0: { id: nanoid(), answer: each.incorrect_answers[0], selected: false },
            incorrect1: { id: nanoid(), answer: each.incorrect_answers[1], selected: false  },
            incorrect2:{ id: nanoid(), answer: each.incorrect_answers[2], selected: false  },
            type: each.type
          }
          })));
 }, [test]);

function startGame() {
  setTest(prevTest => !prevTest)
}

function select(id) {
  console.log(id) // stuck here, don't know how to catch which specific answer is being selected..
  // the id generated by nanoid is for the entire block of answers so isn't enough to differentiate..
  // How can i target each anser selection to toggle its selected property??

    setQuizData(prevQuizData => prevQuizData.map( choice => {
      return choice.correct.id === id ? {...choice, selected: !choice.correct.selected} : choice;
    }))
}

console.log(quizData)

 const questions = quizData.map( (each, index) => {
     return  (
        <div>
            <div className="quest">{each.question}</div>
            <ul className="unselected">

                <li 
                  selected={each.correct.selected} 
                  onClick={()=>select(each.correct.id)}
                  id={each.correct.id}
                  type={each.type}
                  // key={index}
                  >{each.correct.answer}</li>

                <li 
                  selected={each.incorrect0.selected} 
                  onClick={()=>select(each.incorrect0.id)}
                  id={each.incorrect0.id}
                  type={each.type}
                  // key={index}
                >{each.incorrect0.answer}</li>

                {each.incorrect1.answer && <li 
                  selected={each.incorrect1.selected} 
                  onClick={()=>select(each.incorrect1.id)}
                  id={each.incorrect1.id}
                  type={each.type}
                  // key={index}
                >{each.incorrect1.answer}</li>}

                {each.incorrect2.answer &&<li 
                  selected={each.incorrect2.selected} 
                  onClick={()=>select(each.incorrect2.id)}
                  id={each.incorrect2.id}
                  type={each.type}
                  // key={index}
                >{each.incorrect2.answer}</li>}
            </ul>
            <hr />
        </div> 
     )
 });

  return (
    <div className="main">
      {!test && 
        <Cover handleClick={startGame}/>
      }
      {test && 
        <div className="quiz-container">
          {questions}
          <div className="button-box"><button className="submit-button">Check Answers</button></div>
          <div className="button-box">You scored {}/{} correct answers<button className="submit-button">Play Again</button></div>
        </div>
      }
    </div>
  );
}

export default App;
